### ISSUE TITLE
Sass "pseudo" mixin not declared

### ISSUE THREAD

**Issue by 01ssela** [kawishbit/vlider#1]
Hello Kawish, thanks for this component!
I'm inserting it into a project I work on and I wanted to get you noticed
(or ask for explanations, maybe I didn't understand something)

that in "theme"  files (light, dark and purple) you included (line 141) "pseudo" mixin, which is not declared in any other file. this naturally causes an error in the compilation phase!

I simply removed that line, you do what you have to do :) bye!

**Comment by alyoshz** [comment]
And in line 145 there is

@include transform(translateY(-50%));

instead of

transform: translateY(-50%);

**Comment by hwmaier** [comment]
The missing mixins can be found in earlier commits.

As a workaorund they can be added before including the scss file, like shown below:
```
<style lang="scss">
    // Define missing mixins before @include
    @mixin pseudo($display: block, $pos: absolute, $content: '') {
        content: $content;
        display: $display;
        position: $pos;
    }
    @mixin css3-prefix($property, $value) {
        -webkit-#{$property}: #{$value};
        -khtml-#{$property}: #{$value};
        -moz-#{$property}: #{$value};
        -ms-#{$property}: #{$value};
        -o-#{$property}: #{$value};
        #{$property}: #{$value};
    }
    @mixin transform($params) {
        @include css3-prefix('transform', $params);
    }

    @import "vlider/src/sass/vlider.scss";
</style>
           
```
